### ISSUE TITLE
Return express instance from "createServer" function

### ISSUE THREAD

**Issue by tarasromil** [PDFTron/webviewer-html-proxy-server#48]
Hey, for my purpose would be great to have ability setup additional routes for this server.
is there are any blocker to just return "app" instance from "createServer" function to make it work?
Big thanks.

**Comment by maggievu-pdftron** [comment]
Hey @tarasromil,
Thank you for taking the time to report this issue. 

What you're looking to achieve is definitely possible by forking this repository and adding your own customizations.

Thanks again!
